default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "nailmyjob_development") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "postgres") %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  prepared_statements: false

test:
  <<: *default
  database: nailmyjob_test
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "postgres") %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("DATABASE_NAME", "postgres") %>
    username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
    password: <%= ENV.fetch("DATABASE_PASSWORD", "postgres") %>
    host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
    port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
    sslmode: require
    prepared_statements: false
    schema_search_path: public
    variables:
      search_path: public
  cache:
    <<: *default
    database: postgres_cache
    username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
    password: <%= ENV.fetch("DATABASE_PASSWORD", "postgres") %>
    host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
    port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
    sslmode: require
    migrations_paths: db/cache_migrate
    prepared_statements: false
  queue:
    <<: *default
    database: postgres_queue
    username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
    password: <%= ENV.fetch("DATABASE_PASSWORD", "postgres") %>
    host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
    port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
    sslmode: require
    migrations_paths: db/queue_migrate
    prepared_statements: false
  cable:
    <<: *default
    database: postgres_cable
    username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
    password: <%= ENV.fetch("DATABASE_PASSWORD", "postgres") %>
    host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
    port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
    sslmode: require
    migrations_paths: db/cable_migrate
    prepared_statements: false